### IRSYNC server properties ###
server:
  address: 127.0.0.1
  port: 9000
  forward-headers-strategy: native
  servlet:
    context-path: /

# IRSYNC scheduling cron expression
# CSN pushes IR to APs at 4 CET/CEST, so polling for IR from RINA at 15 minutes past the hour between 4 and 6 o'clock is OK
cron:
  expression: 0 15 4-6 * * *

# IRSYNC wait for new IR contents from AP in seconds
update:
  wait: 240

logging:
  config:
    file: .\config\logback-spring.xml


  ### Spring properties ###
spring:
  output:
  ansi:
    enabled: DETECT

spring.main.banner-mode: 'off'
spring.metrics.web.server.auto-time-requests: true

### Metrics ###
management.endpoints.web.exposure.include: info, health, metrics, prometheus, conditions
management.metrics.export.prometheus.enabled: true

rina.tenants:
  - institutionId: NO:889640782
    casBaseUrl: http://localhost/eessiCas
    cpiBaseUrl: http://localhost/eessiRest
    adminuser: admin
    adminpwd: admin123
